sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tQdfRvqdpxFXyDFR5W9
    accessKeySecret: nigVrirDVG63h0jESpa1oJTCL3ZzVI
    bucketName: web-tlias-xzx

  redis:
    host: localhost
    port: 6379
