sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tNFG2feV6eym4d7qkCU
    accessKeySecret: 1QA5xJ2ATMoeOKWtbaD7EWDoi7uYKz
    bucketName: web-tlias-xzx
  redis:
    host: localhost
    port: 6379

  wechat:
    appid: wx3c1174485456cdc6
    secret: 5216666f398722314951cfe0cd7673d8

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-secret-key: itheima
    # 设置jwt过期时间
    user-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
